namespace MusicX.Core.Models.Genius;

public record Annotation(
    string Type,
    string ApiPath,
    bool BeingCreated,
    Body Body,
    int CommentCount,
    bool Community,
    int CreatedAt,
    object CustomPreview,
    bool Deleted,
    string EmbedContent,
    bool HasVoters,
    int Id,
    bool NeedsExegesis,
    bool Pinned,
    int ProposedEditCount,
    object PyongsCount,
    int ReferentId,
    string ShareUrl,
    object Source,
    string State,
    string TwitterShareMessage,
    string Url,
    bool Verified,
    int VotesTotal,
    CurrentUserMetadata CurrentUserMetadata,
    object AcceptedBy,
    IReadOnlyList<Author> Authors,
    IReadOnlyList<object> CosignedBy,
    CreatedBy CreatedBy,
    object RejectionComment,
    object TopComment,
    object VerifiedBy
);