// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: safetyNet.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MusicX.Avalonia.Core.Models.Google {

  /// <summary>Holder for reflection information generated from safetyNet.proto</summary>
  internal static partial class SafetyNetReflection {

    #region Descriptor
    /// <summary>File descriptor for safetyNet.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SafetyNetReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9zYWZldHlOZXQucHJvdG8SIk11c2ljWC5BdmFsb25pYS5Db3JlLk1vZGVs",
            "cy5Hb29nbGUijQIKE0FuZHJvaWRDaGVja2luUHJvdG8SGQoRbGFzdF9jaGVj",
            "a2luX21zZWMYAiABKAMSFQoNY2VsbF9vcGVyYXRvchgGIAEoCRIUCgxzaW1f",
            "b3BlcmF0b3IYByABKAkSDwoHcm9hbWluZxgIIAEoCRITCgt1c2VyX251bWJl",
            "chgJIAEoBRI8CgR0eXBlGAwgASgOMi4uTXVzaWNYLkF2YWxvbmlhLkNvcmUu",
            "TW9kZWxzLkdvb2dsZS5EZXZpY2VUeXBlEkoKDGNocm9tZV9idWlsZBgNIAEo",
            "CzI0Lk11c2ljWC5BdmFsb25pYS5Db3JlLk1vZGVscy5Hb29nbGUuQ2hyb21l",
            "QnVpbGRQcm90byLgAwoVQW5kcm9pZENoZWNraW5SZXF1ZXN0EgwKBGltZWkY",
            "ASABKAkSCgoCaWQYAiABKAMSDgoGZGlnZXN0GAMgASgJEkgKB2NoZWNraW4Y",
            "BCABKAsyNy5NdXNpY1guQXZhbG9uaWEuQ29yZS5Nb2RlbHMuR29vZ2xlLkFu",
            "ZHJvaWRDaGVja2luUHJvdG8SFQoNZGVzaXJlZF9idWlsZBgFIAEoCRIOCgZs",
            "b2NhbGUYBiABKAkSEgoKbG9nZ2luZ19pZBgHIAEoAxIWCg5tYXJrZXRfY2hl",
            "Y2tpbhgIIAEoCRIQCghtYWNfYWRkchgJIAMoCRIMCgRtZWlkGAogASgJEhYK",
            "DmFjY291bnRfY29va2llGAsgAygJEhEKCXRpbWVfem9uZRgMIAEoCRIWCg5z",
            "ZWN1cml0eV90b2tlbhgNIAEoBhIPCgd2ZXJzaW9uGA4gASgFEhAKCG90YV9j",
            "ZXJ0GA8gAygJEhUKDXNlcmlhbF9udW1iZXIYECABKAkSCwoDZXNuGBEgASgJ",
            "EhUKDW1hY19hZGRyX3R5cGUYEyADKAkSEAoIZnJhZ21lbnQYFCABKAUSEQoJ",
            "dXNlcl9uYW1lGBUgASgJEhoKEnVzZXJfc2VyaWFsX251bWJlchgWIAEoBSKY",
            "AgoWQW5kcm9pZENoZWNraW5SZXNwb25zZRIQCghzdGF0c19vaxgBIAEoCBIR",
            "Cgl0aW1lX21zZWMYAyABKAMSDgoGZGlnZXN0GAQgASgJEkUKB3NldHRpbmcY",
            "BSADKAsyNC5NdXNpY1guQXZhbG9uaWEuQ29yZS5Nb2RlbHMuR29vZ2xlLkdz",
            "ZXJ2aWNlc1NldHRpbmcSEQoJbWFya2V0X29rGAYgASgIEhIKCmFuZHJvaWRf",
            "aWQYByABKAYSFgoOc2VjdXJpdHlfdG9rZW4YCCABKAYSFQoNc2V0dGluZ3Nf",
            "ZGlmZhgJIAEoCBIWCg5kZWxldGVfc2V0dGluZxgKIAMoCRIUCgx2ZXJzaW9u",
            "X2luZm8YCyABKAkiqAEKEENocm9tZUJ1aWxkUHJvdG8SPgoIcGxhdGZvcm0Y",
            "ASABKA4yLC5NdXNpY1guQXZhbG9uaWEuQ29yZS5Nb2RlbHMuR29vZ2xlLlBs",
            "YXRmb3JtEhYKDmNocm9tZV92ZXJzaW9uGAIgASgJEjwKB2NoYW5uZWwYAyAB",
            "KA4yKy5NdXNpY1guQXZhbG9uaWEuQ29yZS5Nb2RlbHMuR29vZ2xlLkNoYW5u",
            "ZWwiLwoQR3NlcnZpY2VzU2V0dGluZxIMCgRuYW1lGAEgASgMEg0KBXZhbHVl",
            "GAIgASgMKnMKB0NoYW5uZWwSCAoEWkVSTxAAEhIKDkNIQU5ORUxfU1RBQkxF",
            "EAESEAoMQ0hBTk5FTF9CRVRBEAISDwoLQ0hBTk5FTF9ERVYQAxISCg5DSEFO",
            "TkVMX0NBTkFSWRAEEhMKD0NIQU5ORUxfVU5LTk9XThAFKngKCkRldmljZVR5",
            "cGUSDwoLREVWSUNFX1pFUk8QABIVChFERVZJQ0VfQU5EUk9JRF9PUxABEhEK",
            "DURFVklDRV9JT1NfT1MQAhIZChVERVZJQ0VfQ0hST01FX0JST1dTRVIQAxIU",
            "ChBERVZJQ0VfQ0hST01FX09TEAQqkAEKCFBsYXRmb3JtEhEKDVBMQVRGT1JN",
            "X1pFUk8QABIQCgxQTEFURk9STV9XSU4QARIQCgxQTEFURk9STV9NQUMQAhIS",
            "Cg5QTEFURk9STV9MSU5VWBADEhEKDVBMQVRGT1JNX0NST1MQBBIQCgxQTEFU",
            "Rk9STV9JT1MQBRIUChBQTEFURk9STV9BTkRST0lEEAZiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MusicX.Avalonia.Core.Models.Google.Channel), typeof(global::MusicX.Avalonia.Core.Models.Google.DeviceType), typeof(global::MusicX.Avalonia.Core.Models.Google.Platform), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MusicX.Avalonia.Core.Models.Google.AndroidCheckinProto), global::MusicX.Avalonia.Core.Models.Google.AndroidCheckinProto.Parser, new[]{ "LastCheckinMsec", "CellOperator", "SimOperator", "Roaming", "UserNumber", "Type", "ChromeBuild" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MusicX.Avalonia.Core.Models.Google.AndroidCheckinRequest), global::MusicX.Avalonia.Core.Models.Google.AndroidCheckinRequest.Parser, new[]{ "Imei", "Id", "Digest", "Checkin", "DesiredBuild", "Locale", "LoggingId", "MarketCheckin", "MacAddr", "Meid", "AccountCookie", "TimeZone", "SecurityToken", "Version", "OtaCert", "SerialNumber", "Esn", "MacAddrType", "Fragment", "UserName", "UserSerialNumber" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MusicX.Avalonia.Core.Models.Google.AndroidCheckinResponse), global::MusicX.Avalonia.Core.Models.Google.AndroidCheckinResponse.Parser, new[]{ "StatsOk", "TimeMsec", "Digest", "Setting", "MarketOk", "AndroidId", "SecurityToken", "SettingsDiff", "DeleteSetting", "VersionInfo" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MusicX.Avalonia.Core.Models.Google.ChromeBuildProto), global::MusicX.Avalonia.Core.Models.Google.ChromeBuildProto.Parser, new[]{ "Platform", "ChromeVersion", "Channel" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MusicX.Avalonia.Core.Models.Google.GservicesSetting), global::MusicX.Avalonia.Core.Models.Google.GservicesSetting.Parser, new[]{ "Name", "Value" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  internal enum Channel {
    /// <summary>
    /// proto3 requires a zero value as the first item (it can be named anything)
    /// </summary>
    [pbr::OriginalName("ZERO")] Zero = 0,
    [pbr::OriginalName("CHANNEL_STABLE")] Stable = 1,
    [pbr::OriginalName("CHANNEL_BETA")] Beta = 2,
    [pbr::OriginalName("CHANNEL_DEV")] Dev = 3,
    [pbr::OriginalName("CHANNEL_CANARY")] Canary = 4,
    [pbr::OriginalName("CHANNEL_UNKNOWN")] Unknown = 5,
  }

  internal enum DeviceType {
    /// <summary>
    /// proto3 requires a zero value as the first item (it can be named anything)
    /// </summary>
    [pbr::OriginalName("DEVICE_ZERO")] DeviceZero = 0,
    [pbr::OriginalName("DEVICE_ANDROID_OS")] DeviceAndroidOs = 1,
    [pbr::OriginalName("DEVICE_IOS_OS")] DeviceIosOs = 2,
    [pbr::OriginalName("DEVICE_CHROME_BROWSER")] DeviceChromeBrowser = 3,
    [pbr::OriginalName("DEVICE_CHROME_OS")] DeviceChromeOs = 4,
  }

  internal enum Platform {
    /// <summary>
    /// proto3 requires a zero value as the first item (it can be named anything)
    /// </summary>
    [pbr::OriginalName("PLATFORM_ZERO")] Zero = 0,
    [pbr::OriginalName("PLATFORM_WIN")] Win = 1,
    [pbr::OriginalName("PLATFORM_MAC")] Mac = 2,
    [pbr::OriginalName("PLATFORM_LINUX")] Linux = 3,
    [pbr::OriginalName("PLATFORM_CROS")] Cros = 4,
    [pbr::OriginalName("PLATFORM_IOS")] Ios = 5,
    [pbr::OriginalName("PLATFORM_ANDROID")] Android = 6,
  }

  #endregion

  #region Messages
  internal sealed partial class AndroidCheckinProto : pb::IMessage<AndroidCheckinProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AndroidCheckinProto> _parser = new pb::MessageParser<AndroidCheckinProto>(() => new AndroidCheckinProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AndroidCheckinProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MusicX.Avalonia.Core.Models.Google.SafetyNetReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AndroidCheckinProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AndroidCheckinProto(AndroidCheckinProto other) : this() {
      lastCheckinMsec_ = other.lastCheckinMsec_;
      cellOperator_ = other.cellOperator_;
      simOperator_ = other.simOperator_;
      roaming_ = other.roaming_;
      userNumber_ = other.userNumber_;
      type_ = other.type_;
      chromeBuild_ = other.chromeBuild_ != null ? other.chromeBuild_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AndroidCheckinProto Clone() {
      return new AndroidCheckinProto(this);
    }

    /// <summary>Field number for the "last_checkin_msec" field.</summary>
    public const int LastCheckinMsecFieldNumber = 2;
    private long lastCheckinMsec_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long LastCheckinMsec {
      get { return lastCheckinMsec_; }
      set {
        lastCheckinMsec_ = value;
      }
    }

    /// <summary>Field number for the "cell_operator" field.</summary>
    public const int CellOperatorFieldNumber = 6;
    private string cellOperator_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CellOperator {
      get { return cellOperator_; }
      set {
        cellOperator_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "sim_operator" field.</summary>
    public const int SimOperatorFieldNumber = 7;
    private string simOperator_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SimOperator {
      get { return simOperator_; }
      set {
        simOperator_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "roaming" field.</summary>
    public const int RoamingFieldNumber = 8;
    private string roaming_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Roaming {
      get { return roaming_; }
      set {
        roaming_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "user_number" field.</summary>
    public const int UserNumberFieldNumber = 9;
    private int userNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int UserNumber {
      get { return userNumber_; }
      set {
        userNumber_ = value;
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 12;
    private global::MusicX.Avalonia.Core.Models.Google.DeviceType type_ = global::MusicX.Avalonia.Core.Models.Google.DeviceType.DeviceZero;
    /// <summary>
    /// default value could not be applied: DeviceAndroidOs
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::MusicX.Avalonia.Core.Models.Google.DeviceType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "chrome_build" field.</summary>
    public const int ChromeBuildFieldNumber = 13;
    private global::MusicX.Avalonia.Core.Models.Google.ChromeBuildProto chromeBuild_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::MusicX.Avalonia.Core.Models.Google.ChromeBuildProto ChromeBuild {
      get { return chromeBuild_; }
      set {
        chromeBuild_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AndroidCheckinProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AndroidCheckinProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LastCheckinMsec != other.LastCheckinMsec) return false;
      if (CellOperator != other.CellOperator) return false;
      if (SimOperator != other.SimOperator) return false;
      if (Roaming != other.Roaming) return false;
      if (UserNumber != other.UserNumber) return false;
      if (Type != other.Type) return false;
      if (!object.Equals(ChromeBuild, other.ChromeBuild)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (LastCheckinMsec != 0L) hash ^= LastCheckinMsec.GetHashCode();
      if (CellOperator.Length != 0) hash ^= CellOperator.GetHashCode();
      if (SimOperator.Length != 0) hash ^= SimOperator.GetHashCode();
      if (Roaming.Length != 0) hash ^= Roaming.GetHashCode();
      if (UserNumber != 0) hash ^= UserNumber.GetHashCode();
      if (Type != global::MusicX.Avalonia.Core.Models.Google.DeviceType.DeviceZero) hash ^= Type.GetHashCode();
      if (chromeBuild_ != null) hash ^= ChromeBuild.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (LastCheckinMsec != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(LastCheckinMsec);
      }
      if (CellOperator.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(CellOperator);
      }
      if (SimOperator.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(SimOperator);
      }
      if (Roaming.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Roaming);
      }
      if (UserNumber != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(UserNumber);
      }
      if (Type != global::MusicX.Avalonia.Core.Models.Google.DeviceType.DeviceZero) {
        output.WriteRawTag(96);
        output.WriteEnum((int) Type);
      }
      if (chromeBuild_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(ChromeBuild);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (LastCheckinMsec != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(LastCheckinMsec);
      }
      if (CellOperator.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(CellOperator);
      }
      if (SimOperator.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(SimOperator);
      }
      if (Roaming.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Roaming);
      }
      if (UserNumber != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(UserNumber);
      }
      if (Type != global::MusicX.Avalonia.Core.Models.Google.DeviceType.DeviceZero) {
        output.WriteRawTag(96);
        output.WriteEnum((int) Type);
      }
      if (chromeBuild_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(ChromeBuild);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (LastCheckinMsec != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(LastCheckinMsec);
      }
      if (CellOperator.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CellOperator);
      }
      if (SimOperator.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SimOperator);
      }
      if (Roaming.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Roaming);
      }
      if (UserNumber != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UserNumber);
      }
      if (Type != global::MusicX.Avalonia.Core.Models.Google.DeviceType.DeviceZero) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (chromeBuild_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChromeBuild);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AndroidCheckinProto other) {
      if (other == null) {
        return;
      }
      if (other.LastCheckinMsec != 0L) {
        LastCheckinMsec = other.LastCheckinMsec;
      }
      if (other.CellOperator.Length != 0) {
        CellOperator = other.CellOperator;
      }
      if (other.SimOperator.Length != 0) {
        SimOperator = other.SimOperator;
      }
      if (other.Roaming.Length != 0) {
        Roaming = other.Roaming;
      }
      if (other.UserNumber != 0) {
        UserNumber = other.UserNumber;
      }
      if (other.Type != global::MusicX.Avalonia.Core.Models.Google.DeviceType.DeviceZero) {
        Type = other.Type;
      }
      if (other.chromeBuild_ != null) {
        if (chromeBuild_ == null) {
          ChromeBuild = new global::MusicX.Avalonia.Core.Models.Google.ChromeBuildProto();
        }
        ChromeBuild.MergeFrom(other.ChromeBuild);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 16: {
            LastCheckinMsec = input.ReadInt64();
            break;
          }
          case 50: {
            CellOperator = input.ReadString();
            break;
          }
          case 58: {
            SimOperator = input.ReadString();
            break;
          }
          case 66: {
            Roaming = input.ReadString();
            break;
          }
          case 72: {
            UserNumber = input.ReadInt32();
            break;
          }
          case 96: {
            Type = (global::MusicX.Avalonia.Core.Models.Google.DeviceType) input.ReadEnum();
            break;
          }
          case 106: {
            if (chromeBuild_ == null) {
              ChromeBuild = new global::MusicX.Avalonia.Core.Models.Google.ChromeBuildProto();
            }
            input.ReadMessage(ChromeBuild);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 16: {
            LastCheckinMsec = input.ReadInt64();
            break;
          }
          case 50: {
            CellOperator = input.ReadString();
            break;
          }
          case 58: {
            SimOperator = input.ReadString();
            break;
          }
          case 66: {
            Roaming = input.ReadString();
            break;
          }
          case 72: {
            UserNumber = input.ReadInt32();
            break;
          }
          case 96: {
            Type = (global::MusicX.Avalonia.Core.Models.Google.DeviceType) input.ReadEnum();
            break;
          }
          case 106: {
            if (chromeBuild_ == null) {
              ChromeBuild = new global::MusicX.Avalonia.Core.Models.Google.ChromeBuildProto();
            }
            input.ReadMessage(ChromeBuild);
            break;
          }
        }
      }
    }
    #endif

  }

  internal sealed partial class AndroidCheckinRequest : pb::IMessage<AndroidCheckinRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AndroidCheckinRequest> _parser = new pb::MessageParser<AndroidCheckinRequest>(() => new AndroidCheckinRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AndroidCheckinRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MusicX.Avalonia.Core.Models.Google.SafetyNetReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AndroidCheckinRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AndroidCheckinRequest(AndroidCheckinRequest other) : this() {
      imei_ = other.imei_;
      id_ = other.id_;
      digest_ = other.digest_;
      checkin_ = other.checkin_ != null ? other.checkin_.Clone() : null;
      desiredBuild_ = other.desiredBuild_;
      locale_ = other.locale_;
      loggingId_ = other.loggingId_;
      marketCheckin_ = other.marketCheckin_;
      macAddr_ = other.macAddr_.Clone();
      meid_ = other.meid_;
      accountCookie_ = other.accountCookie_.Clone();
      timeZone_ = other.timeZone_;
      securityToken_ = other.securityToken_;
      version_ = other.version_;
      otaCert_ = other.otaCert_.Clone();
      serialNumber_ = other.serialNumber_;
      esn_ = other.esn_;
      macAddrType_ = other.macAddrType_.Clone();
      fragment_ = other.fragment_;
      userName_ = other.userName_;
      userSerialNumber_ = other.userSerialNumber_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AndroidCheckinRequest Clone() {
      return new AndroidCheckinRequest(this);
    }

    /// <summary>Field number for the "imei" field.</summary>
    public const int ImeiFieldNumber = 1;
    private string imei_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Imei {
      get { return imei_; }
      set {
        imei_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 2;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "digest" field.</summary>
    public const int DigestFieldNumber = 3;
    private string digest_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Digest {
      get { return digest_; }
      set {
        digest_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "checkin" field.</summary>
    public const int CheckinFieldNumber = 4;
    private global::MusicX.Avalonia.Core.Models.Google.AndroidCheckinProto checkin_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::MusicX.Avalonia.Core.Models.Google.AndroidCheckinProto Checkin {
      get { return checkin_; }
      set {
        checkin_ = value;
      }
    }

    /// <summary>Field number for the "desired_build" field.</summary>
    public const int DesiredBuildFieldNumber = 5;
    private string desiredBuild_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DesiredBuild {
      get { return desiredBuild_; }
      set {
        desiredBuild_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "locale" field.</summary>
    public const int LocaleFieldNumber = 6;
    private string locale_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Locale {
      get { return locale_; }
      set {
        locale_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "logging_id" field.</summary>
    public const int LoggingIdFieldNumber = 7;
    private long loggingId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long LoggingId {
      get { return loggingId_; }
      set {
        loggingId_ = value;
      }
    }

    /// <summary>Field number for the "market_checkin" field.</summary>
    public const int MarketCheckinFieldNumber = 8;
    private string marketCheckin_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MarketCheckin {
      get { return marketCheckin_; }
      set {
        marketCheckin_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "mac_addr" field.</summary>
    public const int MacAddrFieldNumber = 9;
    private static readonly pb::FieldCodec<string> _repeated_macAddr_codec
        = pb::FieldCodec.ForString(74);
    private readonly pbc::RepeatedField<string> macAddr_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> MacAddr {
      get { return macAddr_; }
    }

    /// <summary>Field number for the "meid" field.</summary>
    public const int MeidFieldNumber = 10;
    private string meid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Meid {
      get { return meid_; }
      set {
        meid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "account_cookie" field.</summary>
    public const int AccountCookieFieldNumber = 11;
    private static readonly pb::FieldCodec<string> _repeated_accountCookie_codec
        = pb::FieldCodec.ForString(90);
    private readonly pbc::RepeatedField<string> accountCookie_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> AccountCookie {
      get { return accountCookie_; }
    }

    /// <summary>Field number for the "time_zone" field.</summary>
    public const int TimeZoneFieldNumber = 12;
    private string timeZone_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TimeZone {
      get { return timeZone_; }
      set {
        timeZone_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "security_token" field.</summary>
    public const int SecurityTokenFieldNumber = 13;
    private ulong securityToken_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong SecurityToken {
      get { return securityToken_; }
      set {
        securityToken_ = value;
      }
    }

    /// <summary>Field number for the "version" field.</summary>
    public const int VersionFieldNumber = 14;
    private int version_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Version {
      get { return version_; }
      set {
        version_ = value;
      }
    }

    /// <summary>Field number for the "ota_cert" field.</summary>
    public const int OtaCertFieldNumber = 15;
    private static readonly pb::FieldCodec<string> _repeated_otaCert_codec
        = pb::FieldCodec.ForString(122);
    private readonly pbc::RepeatedField<string> otaCert_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> OtaCert {
      get { return otaCert_; }
    }

    /// <summary>Field number for the "serial_number" field.</summary>
    public const int SerialNumberFieldNumber = 16;
    private string serialNumber_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SerialNumber {
      get { return serialNumber_; }
      set {
        serialNumber_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "esn" field.</summary>
    public const int EsnFieldNumber = 17;
    private string esn_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Esn {
      get { return esn_; }
      set {
        esn_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "mac_addr_type" field.</summary>
    public const int MacAddrTypeFieldNumber = 19;
    private static readonly pb::FieldCodec<string> _repeated_macAddrType_codec
        = pb::FieldCodec.ForString(154);
    private readonly pbc::RepeatedField<string> macAddrType_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> MacAddrType {
      get { return macAddrType_; }
    }

    /// <summary>Field number for the "fragment" field.</summary>
    public const int FragmentFieldNumber = 20;
    private int fragment_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Fragment {
      get { return fragment_; }
      set {
        fragment_ = value;
      }
    }

    /// <summary>Field number for the "user_name" field.</summary>
    public const int UserNameFieldNumber = 21;
    private string userName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UserName {
      get { return userName_; }
      set {
        userName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "user_serial_number" field.</summary>
    public const int UserSerialNumberFieldNumber = 22;
    private int userSerialNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int UserSerialNumber {
      get { return userSerialNumber_; }
      set {
        userSerialNumber_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AndroidCheckinRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AndroidCheckinRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Imei != other.Imei) return false;
      if (Id != other.Id) return false;
      if (Digest != other.Digest) return false;
      if (!object.Equals(Checkin, other.Checkin)) return false;
      if (DesiredBuild != other.DesiredBuild) return false;
      if (Locale != other.Locale) return false;
      if (LoggingId != other.LoggingId) return false;
      if (MarketCheckin != other.MarketCheckin) return false;
      if(!macAddr_.Equals(other.macAddr_)) return false;
      if (Meid != other.Meid) return false;
      if(!accountCookie_.Equals(other.accountCookie_)) return false;
      if (TimeZone != other.TimeZone) return false;
      if (SecurityToken != other.SecurityToken) return false;
      if (Version != other.Version) return false;
      if(!otaCert_.Equals(other.otaCert_)) return false;
      if (SerialNumber != other.SerialNumber) return false;
      if (Esn != other.Esn) return false;
      if(!macAddrType_.Equals(other.macAddrType_)) return false;
      if (Fragment != other.Fragment) return false;
      if (UserName != other.UserName) return false;
      if (UserSerialNumber != other.UserSerialNumber) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Imei.Length != 0) hash ^= Imei.GetHashCode();
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (Digest.Length != 0) hash ^= Digest.GetHashCode();
      if (checkin_ != null) hash ^= Checkin.GetHashCode();
      if (DesiredBuild.Length != 0) hash ^= DesiredBuild.GetHashCode();
      if (Locale.Length != 0) hash ^= Locale.GetHashCode();
      if (LoggingId != 0L) hash ^= LoggingId.GetHashCode();
      if (MarketCheckin.Length != 0) hash ^= MarketCheckin.GetHashCode();
      hash ^= macAddr_.GetHashCode();
      if (Meid.Length != 0) hash ^= Meid.GetHashCode();
      hash ^= accountCookie_.GetHashCode();
      if (TimeZone.Length != 0) hash ^= TimeZone.GetHashCode();
      if (SecurityToken != 0UL) hash ^= SecurityToken.GetHashCode();
      if (Version != 0) hash ^= Version.GetHashCode();
      hash ^= otaCert_.GetHashCode();
      if (SerialNumber.Length != 0) hash ^= SerialNumber.GetHashCode();
      if (Esn.Length != 0) hash ^= Esn.GetHashCode();
      hash ^= macAddrType_.GetHashCode();
      if (Fragment != 0) hash ^= Fragment.GetHashCode();
      if (UserName.Length != 0) hash ^= UserName.GetHashCode();
      if (UserSerialNumber != 0) hash ^= UserSerialNumber.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Imei.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Imei);
      }
      if (Id != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Id);
      }
      if (Digest.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Digest);
      }
      if (checkin_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Checkin);
      }
      if (DesiredBuild.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(DesiredBuild);
      }
      if (Locale.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Locale);
      }
      if (LoggingId != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(LoggingId);
      }
      if (MarketCheckin.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(MarketCheckin);
      }
      macAddr_.WriteTo(output, _repeated_macAddr_codec);
      if (Meid.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Meid);
      }
      accountCookie_.WriteTo(output, _repeated_accountCookie_codec);
      if (TimeZone.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(TimeZone);
      }
      if (SecurityToken != 0UL) {
        output.WriteRawTag(105);
        output.WriteFixed64(SecurityToken);
      }
      if (Version != 0) {
        output.WriteRawTag(112);
        output.WriteInt32(Version);
      }
      otaCert_.WriteTo(output, _repeated_otaCert_codec);
      if (SerialNumber.Length != 0) {
        output.WriteRawTag(130, 1);
        output.WriteString(SerialNumber);
      }
      if (Esn.Length != 0) {
        output.WriteRawTag(138, 1);
        output.WriteString(Esn);
      }
      macAddrType_.WriteTo(output, _repeated_macAddrType_codec);
      if (Fragment != 0) {
        output.WriteRawTag(160, 1);
        output.WriteInt32(Fragment);
      }
      if (UserName.Length != 0) {
        output.WriteRawTag(170, 1);
        output.WriteString(UserName);
      }
      if (UserSerialNumber != 0) {
        output.WriteRawTag(176, 1);
        output.WriteInt32(UserSerialNumber);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Imei.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Imei);
      }
      if (Id != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Id);
      }
      if (Digest.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Digest);
      }
      if (checkin_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Checkin);
      }
      if (DesiredBuild.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(DesiredBuild);
      }
      if (Locale.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Locale);
      }
      if (LoggingId != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(LoggingId);
      }
      if (MarketCheckin.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(MarketCheckin);
      }
      macAddr_.WriteTo(ref output, _repeated_macAddr_codec);
      if (Meid.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Meid);
      }
      accountCookie_.WriteTo(ref output, _repeated_accountCookie_codec);
      if (TimeZone.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(TimeZone);
      }
      if (SecurityToken != 0UL) {
        output.WriteRawTag(105);
        output.WriteFixed64(SecurityToken);
      }
      if (Version != 0) {
        output.WriteRawTag(112);
        output.WriteInt32(Version);
      }
      otaCert_.WriteTo(ref output, _repeated_otaCert_codec);
      if (SerialNumber.Length != 0) {
        output.WriteRawTag(130, 1);
        output.WriteString(SerialNumber);
      }
      if (Esn.Length != 0) {
        output.WriteRawTag(138, 1);
        output.WriteString(Esn);
      }
      macAddrType_.WriteTo(ref output, _repeated_macAddrType_codec);
      if (Fragment != 0) {
        output.WriteRawTag(160, 1);
        output.WriteInt32(Fragment);
      }
      if (UserName.Length != 0) {
        output.WriteRawTag(170, 1);
        output.WriteString(UserName);
      }
      if (UserSerialNumber != 0) {
        output.WriteRawTag(176, 1);
        output.WriteInt32(UserSerialNumber);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Imei.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Imei);
      }
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (Digest.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Digest);
      }
      if (checkin_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Checkin);
      }
      if (DesiredBuild.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DesiredBuild);
      }
      if (Locale.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Locale);
      }
      if (LoggingId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(LoggingId);
      }
      if (MarketCheckin.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MarketCheckin);
      }
      size += macAddr_.CalculateSize(_repeated_macAddr_codec);
      if (Meid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Meid);
      }
      size += accountCookie_.CalculateSize(_repeated_accountCookie_codec);
      if (TimeZone.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TimeZone);
      }
      if (SecurityToken != 0UL) {
        size += 1 + 8;
      }
      if (Version != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Version);
      }
      size += otaCert_.CalculateSize(_repeated_otaCert_codec);
      if (SerialNumber.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(SerialNumber);
      }
      if (Esn.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Esn);
      }
      size += macAddrType_.CalculateSize(_repeated_macAddrType_codec);
      if (Fragment != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Fragment);
      }
      if (UserName.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(UserName);
      }
      if (UserSerialNumber != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(UserSerialNumber);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AndroidCheckinRequest other) {
      if (other == null) {
        return;
      }
      if (other.Imei.Length != 0) {
        Imei = other.Imei;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.Digest.Length != 0) {
        Digest = other.Digest;
      }
      if (other.checkin_ != null) {
        if (checkin_ == null) {
          Checkin = new global::MusicX.Avalonia.Core.Models.Google.AndroidCheckinProto();
        }
        Checkin.MergeFrom(other.Checkin);
      }
      if (other.DesiredBuild.Length != 0) {
        DesiredBuild = other.DesiredBuild;
      }
      if (other.Locale.Length != 0) {
        Locale = other.Locale;
      }
      if (other.LoggingId != 0L) {
        LoggingId = other.LoggingId;
      }
      if (other.MarketCheckin.Length != 0) {
        MarketCheckin = other.MarketCheckin;
      }
      macAddr_.Add(other.macAddr_);
      if (other.Meid.Length != 0) {
        Meid = other.Meid;
      }
      accountCookie_.Add(other.accountCookie_);
      if (other.TimeZone.Length != 0) {
        TimeZone = other.TimeZone;
      }
      if (other.SecurityToken != 0UL) {
        SecurityToken = other.SecurityToken;
      }
      if (other.Version != 0) {
        Version = other.Version;
      }
      otaCert_.Add(other.otaCert_);
      if (other.SerialNumber.Length != 0) {
        SerialNumber = other.SerialNumber;
      }
      if (other.Esn.Length != 0) {
        Esn = other.Esn;
      }
      macAddrType_.Add(other.macAddrType_);
      if (other.Fragment != 0) {
        Fragment = other.Fragment;
      }
      if (other.UserName.Length != 0) {
        UserName = other.UserName;
      }
      if (other.UserSerialNumber != 0) {
        UserSerialNumber = other.UserSerialNumber;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Imei = input.ReadString();
            break;
          }
          case 16: {
            Id = input.ReadInt64();
            break;
          }
          case 26: {
            Digest = input.ReadString();
            break;
          }
          case 34: {
            if (checkin_ == null) {
              Checkin = new global::MusicX.Avalonia.Core.Models.Google.AndroidCheckinProto();
            }
            input.ReadMessage(Checkin);
            break;
          }
          case 42: {
            DesiredBuild = input.ReadString();
            break;
          }
          case 50: {
            Locale = input.ReadString();
            break;
          }
          case 56: {
            LoggingId = input.ReadInt64();
            break;
          }
          case 66: {
            MarketCheckin = input.ReadString();
            break;
          }
          case 74: {
            macAddr_.AddEntriesFrom(input, _repeated_macAddr_codec);
            break;
          }
          case 82: {
            Meid = input.ReadString();
            break;
          }
          case 90: {
            accountCookie_.AddEntriesFrom(input, _repeated_accountCookie_codec);
            break;
          }
          case 98: {
            TimeZone = input.ReadString();
            break;
          }
          case 105: {
            SecurityToken = input.ReadFixed64();
            break;
          }
          case 112: {
            Version = input.ReadInt32();
            break;
          }
          case 122: {
            otaCert_.AddEntriesFrom(input, _repeated_otaCert_codec);
            break;
          }
          case 130: {
            SerialNumber = input.ReadString();
            break;
          }
          case 138: {
            Esn = input.ReadString();
            break;
          }
          case 154: {
            macAddrType_.AddEntriesFrom(input, _repeated_macAddrType_codec);
            break;
          }
          case 160: {
            Fragment = input.ReadInt32();
            break;
          }
          case 170: {
            UserName = input.ReadString();
            break;
          }
          case 176: {
            UserSerialNumber = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Imei = input.ReadString();
            break;
          }
          case 16: {
            Id = input.ReadInt64();
            break;
          }
          case 26: {
            Digest = input.ReadString();
            break;
          }
          case 34: {
            if (checkin_ == null) {
              Checkin = new global::MusicX.Avalonia.Core.Models.Google.AndroidCheckinProto();
            }
            input.ReadMessage(Checkin);
            break;
          }
          case 42: {
            DesiredBuild = input.ReadString();
            break;
          }
          case 50: {
            Locale = input.ReadString();
            break;
          }
          case 56: {
            LoggingId = input.ReadInt64();
            break;
          }
          case 66: {
            MarketCheckin = input.ReadString();
            break;
          }
          case 74: {
            macAddr_.AddEntriesFrom(ref input, _repeated_macAddr_codec);
            break;
          }
          case 82: {
            Meid = input.ReadString();
            break;
          }
          case 90: {
            accountCookie_.AddEntriesFrom(ref input, _repeated_accountCookie_codec);
            break;
          }
          case 98: {
            TimeZone = input.ReadString();
            break;
          }
          case 105: {
            SecurityToken = input.ReadFixed64();
            break;
          }
          case 112: {
            Version = input.ReadInt32();
            break;
          }
          case 122: {
            otaCert_.AddEntriesFrom(ref input, _repeated_otaCert_codec);
            break;
          }
          case 130: {
            SerialNumber = input.ReadString();
            break;
          }
          case 138: {
            Esn = input.ReadString();
            break;
          }
          case 154: {
            macAddrType_.AddEntriesFrom(ref input, _repeated_macAddrType_codec);
            break;
          }
          case 160: {
            Fragment = input.ReadInt32();
            break;
          }
          case 170: {
            UserName = input.ReadString();
            break;
          }
          case 176: {
            UserSerialNumber = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  internal sealed partial class AndroidCheckinResponse : pb::IMessage<AndroidCheckinResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AndroidCheckinResponse> _parser = new pb::MessageParser<AndroidCheckinResponse>(() => new AndroidCheckinResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AndroidCheckinResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MusicX.Avalonia.Core.Models.Google.SafetyNetReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AndroidCheckinResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AndroidCheckinResponse(AndroidCheckinResponse other) : this() {
      statsOk_ = other.statsOk_;
      timeMsec_ = other.timeMsec_;
      digest_ = other.digest_;
      setting_ = other.setting_.Clone();
      marketOk_ = other.marketOk_;
      androidId_ = other.androidId_;
      securityToken_ = other.securityToken_;
      settingsDiff_ = other.settingsDiff_;
      deleteSetting_ = other.deleteSetting_.Clone();
      versionInfo_ = other.versionInfo_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AndroidCheckinResponse Clone() {
      return new AndroidCheckinResponse(this);
    }

    /// <summary>Field number for the "stats_ok" field.</summary>
    public const int StatsOkFieldNumber = 1;
    private bool statsOk_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool StatsOk {
      get { return statsOk_; }
      set {
        statsOk_ = value;
      }
    }

    /// <summary>Field number for the "time_msec" field.</summary>
    public const int TimeMsecFieldNumber = 3;
    private long timeMsec_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TimeMsec {
      get { return timeMsec_; }
      set {
        timeMsec_ = value;
      }
    }

    /// <summary>Field number for the "digest" field.</summary>
    public const int DigestFieldNumber = 4;
    private string digest_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Digest {
      get { return digest_; }
      set {
        digest_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "setting" field.</summary>
    public const int SettingFieldNumber = 5;
    private static readonly pb::FieldCodec<global::MusicX.Avalonia.Core.Models.Google.GservicesSetting> _repeated_setting_codec
        = pb::FieldCodec.ForMessage(42, global::MusicX.Avalonia.Core.Models.Google.GservicesSetting.Parser);
    private readonly pbc::RepeatedField<global::MusicX.Avalonia.Core.Models.Google.GservicesSetting> setting_ = new pbc::RepeatedField<global::MusicX.Avalonia.Core.Models.Google.GservicesSetting>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::MusicX.Avalonia.Core.Models.Google.GservicesSetting> Setting {
      get { return setting_; }
    }

    /// <summary>Field number for the "market_ok" field.</summary>
    public const int MarketOkFieldNumber = 6;
    private bool marketOk_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool MarketOk {
      get { return marketOk_; }
      set {
        marketOk_ = value;
      }
    }

    /// <summary>Field number for the "android_id" field.</summary>
    public const int AndroidIdFieldNumber = 7;
    private ulong androidId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong AndroidId {
      get { return androidId_; }
      set {
        androidId_ = value;
      }
    }

    /// <summary>Field number for the "security_token" field.</summary>
    public const int SecurityTokenFieldNumber = 8;
    private ulong securityToken_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong SecurityToken {
      get { return securityToken_; }
      set {
        securityToken_ = value;
      }
    }

    /// <summary>Field number for the "settings_diff" field.</summary>
    public const int SettingsDiffFieldNumber = 9;
    private bool settingsDiff_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool SettingsDiff {
      get { return settingsDiff_; }
      set {
        settingsDiff_ = value;
      }
    }

    /// <summary>Field number for the "delete_setting" field.</summary>
    public const int DeleteSettingFieldNumber = 10;
    private static readonly pb::FieldCodec<string> _repeated_deleteSetting_codec
        = pb::FieldCodec.ForString(82);
    private readonly pbc::RepeatedField<string> deleteSetting_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> DeleteSetting {
      get { return deleteSetting_; }
    }

    /// <summary>Field number for the "version_info" field.</summary>
    public const int VersionInfoFieldNumber = 11;
    private string versionInfo_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string VersionInfo {
      get { return versionInfo_; }
      set {
        versionInfo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AndroidCheckinResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AndroidCheckinResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StatsOk != other.StatsOk) return false;
      if (TimeMsec != other.TimeMsec) return false;
      if (Digest != other.Digest) return false;
      if(!setting_.Equals(other.setting_)) return false;
      if (MarketOk != other.MarketOk) return false;
      if (AndroidId != other.AndroidId) return false;
      if (SecurityToken != other.SecurityToken) return false;
      if (SettingsDiff != other.SettingsDiff) return false;
      if(!deleteSetting_.Equals(other.deleteSetting_)) return false;
      if (VersionInfo != other.VersionInfo) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (StatsOk != false) hash ^= StatsOk.GetHashCode();
      if (TimeMsec != 0L) hash ^= TimeMsec.GetHashCode();
      if (Digest.Length != 0) hash ^= Digest.GetHashCode();
      hash ^= setting_.GetHashCode();
      if (MarketOk != false) hash ^= MarketOk.GetHashCode();
      if (AndroidId != 0UL) hash ^= AndroidId.GetHashCode();
      if (SecurityToken != 0UL) hash ^= SecurityToken.GetHashCode();
      if (SettingsDiff != false) hash ^= SettingsDiff.GetHashCode();
      hash ^= deleteSetting_.GetHashCode();
      if (VersionInfo.Length != 0) hash ^= VersionInfo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (StatsOk != false) {
        output.WriteRawTag(8);
        output.WriteBool(StatsOk);
      }
      if (TimeMsec != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(TimeMsec);
      }
      if (Digest.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Digest);
      }
      setting_.WriteTo(output, _repeated_setting_codec);
      if (MarketOk != false) {
        output.WriteRawTag(48);
        output.WriteBool(MarketOk);
      }
      if (AndroidId != 0UL) {
        output.WriteRawTag(57);
        output.WriteFixed64(AndroidId);
      }
      if (SecurityToken != 0UL) {
        output.WriteRawTag(65);
        output.WriteFixed64(SecurityToken);
      }
      if (SettingsDiff != false) {
        output.WriteRawTag(72);
        output.WriteBool(SettingsDiff);
      }
      deleteSetting_.WriteTo(output, _repeated_deleteSetting_codec);
      if (VersionInfo.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(VersionInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (StatsOk != false) {
        output.WriteRawTag(8);
        output.WriteBool(StatsOk);
      }
      if (TimeMsec != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(TimeMsec);
      }
      if (Digest.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Digest);
      }
      setting_.WriteTo(ref output, _repeated_setting_codec);
      if (MarketOk != false) {
        output.WriteRawTag(48);
        output.WriteBool(MarketOk);
      }
      if (AndroidId != 0UL) {
        output.WriteRawTag(57);
        output.WriteFixed64(AndroidId);
      }
      if (SecurityToken != 0UL) {
        output.WriteRawTag(65);
        output.WriteFixed64(SecurityToken);
      }
      if (SettingsDiff != false) {
        output.WriteRawTag(72);
        output.WriteBool(SettingsDiff);
      }
      deleteSetting_.WriteTo(ref output, _repeated_deleteSetting_codec);
      if (VersionInfo.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(VersionInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (StatsOk != false) {
        size += 1 + 1;
      }
      if (TimeMsec != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TimeMsec);
      }
      if (Digest.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Digest);
      }
      size += setting_.CalculateSize(_repeated_setting_codec);
      if (MarketOk != false) {
        size += 1 + 1;
      }
      if (AndroidId != 0UL) {
        size += 1 + 8;
      }
      if (SecurityToken != 0UL) {
        size += 1 + 8;
      }
      if (SettingsDiff != false) {
        size += 1 + 1;
      }
      size += deleteSetting_.CalculateSize(_repeated_deleteSetting_codec);
      if (VersionInfo.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(VersionInfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AndroidCheckinResponse other) {
      if (other == null) {
        return;
      }
      if (other.StatsOk != false) {
        StatsOk = other.StatsOk;
      }
      if (other.TimeMsec != 0L) {
        TimeMsec = other.TimeMsec;
      }
      if (other.Digest.Length != 0) {
        Digest = other.Digest;
      }
      setting_.Add(other.setting_);
      if (other.MarketOk != false) {
        MarketOk = other.MarketOk;
      }
      if (other.AndroidId != 0UL) {
        AndroidId = other.AndroidId;
      }
      if (other.SecurityToken != 0UL) {
        SecurityToken = other.SecurityToken;
      }
      if (other.SettingsDiff != false) {
        SettingsDiff = other.SettingsDiff;
      }
      deleteSetting_.Add(other.deleteSetting_);
      if (other.VersionInfo.Length != 0) {
        VersionInfo = other.VersionInfo;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StatsOk = input.ReadBool();
            break;
          }
          case 24: {
            TimeMsec = input.ReadInt64();
            break;
          }
          case 34: {
            Digest = input.ReadString();
            break;
          }
          case 42: {
            setting_.AddEntriesFrom(input, _repeated_setting_codec);
            break;
          }
          case 48: {
            MarketOk = input.ReadBool();
            break;
          }
          case 57: {
            AndroidId = input.ReadFixed64();
            break;
          }
          case 65: {
            SecurityToken = input.ReadFixed64();
            break;
          }
          case 72: {
            SettingsDiff = input.ReadBool();
            break;
          }
          case 82: {
            deleteSetting_.AddEntriesFrom(input, _repeated_deleteSetting_codec);
            break;
          }
          case 90: {
            VersionInfo = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            StatsOk = input.ReadBool();
            break;
          }
          case 24: {
            TimeMsec = input.ReadInt64();
            break;
          }
          case 34: {
            Digest = input.ReadString();
            break;
          }
          case 42: {
            setting_.AddEntriesFrom(ref input, _repeated_setting_codec);
            break;
          }
          case 48: {
            MarketOk = input.ReadBool();
            break;
          }
          case 57: {
            AndroidId = input.ReadFixed64();
            break;
          }
          case 65: {
            SecurityToken = input.ReadFixed64();
            break;
          }
          case 72: {
            SettingsDiff = input.ReadBool();
            break;
          }
          case 82: {
            deleteSetting_.AddEntriesFrom(ref input, _repeated_deleteSetting_codec);
            break;
          }
          case 90: {
            VersionInfo = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  internal sealed partial class ChromeBuildProto : pb::IMessage<ChromeBuildProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ChromeBuildProto> _parser = new pb::MessageParser<ChromeBuildProto>(() => new ChromeBuildProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ChromeBuildProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MusicX.Avalonia.Core.Models.Google.SafetyNetReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChromeBuildProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChromeBuildProto(ChromeBuildProto other) : this() {
      platform_ = other.platform_;
      chromeVersion_ = other.chromeVersion_;
      channel_ = other.channel_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChromeBuildProto Clone() {
      return new ChromeBuildProto(this);
    }

    /// <summary>Field number for the "platform" field.</summary>
    public const int PlatformFieldNumber = 1;
    private global::MusicX.Avalonia.Core.Models.Google.Platform platform_ = global::MusicX.Avalonia.Core.Models.Google.Platform.Zero;
    /// <summary>
    /// default value could not be applied: PlatformWin
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::MusicX.Avalonia.Core.Models.Google.Platform Platform {
      get { return platform_; }
      set {
        platform_ = value;
      }
    }

    /// <summary>Field number for the "chrome_version" field.</summary>
    public const int ChromeVersionFieldNumber = 2;
    private string chromeVersion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ChromeVersion {
      get { return chromeVersion_; }
      set {
        chromeVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "channel" field.</summary>
    public const int ChannelFieldNumber = 3;
    private global::MusicX.Avalonia.Core.Models.Google.Channel channel_ = global::MusicX.Avalonia.Core.Models.Google.Channel.Zero;
    /// <summary>
    /// default value could not be applied: ChannelStable
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::MusicX.Avalonia.Core.Models.Google.Channel Channel {
      get { return channel_; }
      set {
        channel_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ChromeBuildProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ChromeBuildProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Platform != other.Platform) return false;
      if (ChromeVersion != other.ChromeVersion) return false;
      if (Channel != other.Channel) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Platform != global::MusicX.Avalonia.Core.Models.Google.Platform.Zero) hash ^= Platform.GetHashCode();
      if (ChromeVersion.Length != 0) hash ^= ChromeVersion.GetHashCode();
      if (Channel != global::MusicX.Avalonia.Core.Models.Google.Channel.Zero) hash ^= Channel.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Platform != global::MusicX.Avalonia.Core.Models.Google.Platform.Zero) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Platform);
      }
      if (ChromeVersion.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ChromeVersion);
      }
      if (Channel != global::MusicX.Avalonia.Core.Models.Google.Channel.Zero) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Channel);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Platform != global::MusicX.Avalonia.Core.Models.Google.Platform.Zero) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Platform);
      }
      if (ChromeVersion.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ChromeVersion);
      }
      if (Channel != global::MusicX.Avalonia.Core.Models.Google.Channel.Zero) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Channel);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Platform != global::MusicX.Avalonia.Core.Models.Google.Platform.Zero) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Platform);
      }
      if (ChromeVersion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ChromeVersion);
      }
      if (Channel != global::MusicX.Avalonia.Core.Models.Google.Channel.Zero) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Channel);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ChromeBuildProto other) {
      if (other == null) {
        return;
      }
      if (other.Platform != global::MusicX.Avalonia.Core.Models.Google.Platform.Zero) {
        Platform = other.Platform;
      }
      if (other.ChromeVersion.Length != 0) {
        ChromeVersion = other.ChromeVersion;
      }
      if (other.Channel != global::MusicX.Avalonia.Core.Models.Google.Channel.Zero) {
        Channel = other.Channel;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Platform = (global::MusicX.Avalonia.Core.Models.Google.Platform) input.ReadEnum();
            break;
          }
          case 18: {
            ChromeVersion = input.ReadString();
            break;
          }
          case 24: {
            Channel = (global::MusicX.Avalonia.Core.Models.Google.Channel) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Platform = (global::MusicX.Avalonia.Core.Models.Google.Platform) input.ReadEnum();
            break;
          }
          case 18: {
            ChromeVersion = input.ReadString();
            break;
          }
          case 24: {
            Channel = (global::MusicX.Avalonia.Core.Models.Google.Channel) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  internal sealed partial class GservicesSetting : pb::IMessage<GservicesSetting>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GservicesSetting> _parser = new pb::MessageParser<GservicesSetting>(() => new GservicesSetting());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GservicesSetting> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MusicX.Avalonia.Core.Models.Google.SafetyNetReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GservicesSetting() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GservicesSetting(GservicesSetting other) : this() {
      name_ = other.name_;
      value_ = other.value_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GservicesSetting Clone() {
      return new GservicesSetting(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private pb::ByteString name_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 2;
    private pb::ByteString value_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Value {
      get { return value_; }
      set {
        value_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GservicesSetting);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GservicesSetting other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Value != other.Value) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Value.Length != 0) hash ^= Value.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Name);
      }
      if (Value.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Value);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Name);
      }
      if (Value.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Value);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Name);
      }
      if (Value.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Value);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GservicesSetting other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Value.Length != 0) {
        Value = other.Value;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadBytes();
            break;
          }
          case 18: {
            Value = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadBytes();
            break;
          }
          case 18: {
            Value = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
