name: .NET

on:
  push:
    branches: [ master ]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  compute-version:
    name: Compute Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1
  
  build:

    runs-on: windows-latest
    needs: [compute-version]

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore MusicX/MusicX.csproj --locked-mode
        
    - name: Build
      run: dotnet publish MusicX/MusicX.csproj --no-restore -o pub -p:Platform=x64 -p:Version=${{ needs.compute-version.outputs.version }} -c Release -r win10-x64 --sc
    
    - name: Install csq
      run: dotnet tool install --global csq
      
    - name: Build package
      run: csq --csq-version=3.0.210-g5f9f594 pack -r rel -p pub -u MusicX.WPF -v ${{ needs.compute-version.outputs.version }} --packTitle "MusicX Player" -e MusicX.exe -i MusicX/StoreLogo.scale-400.ico --appIcon MusicX/StoreLogo.scale-400.ico --msi x64 --includePdb --packAuthors "Fooxboy, zznty and testers" --releaseNotes notes.md -s MusicX/StoreLogo.scale-400.png
      
    - name: Push package
      run: csq --csq-version=3.0.210-g5f9f594 github-up -r rel --repoUrl https://github.com/fooxboy/musicxreleases --publish --token ${{ secrets.GITHUB_TOKEN }}
